

services:
  db:
    image: postgres:15-alpine
    container_name: fultang_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=fulltang_db
      - POSTGRES_USER=fulltang_user
      - POSTGRES_PASSWORD=fulltang_password_2026
    ports:
      - "5432:5432"
    networks:
      - fultang
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fulltang_user -d fulltang_db"]
      interval: 10s
      timeout: 5s
      retries: 5


  fultang:
    build:
      context: . # dossier courant
      dockerfile: Dockerfile
    image: "${FULTANG_IMAGE:-fultang:latest}"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8009:8009"

    env_file:
      - .env
    networks:
      - fultang
    container_name: fultang
    depends_on:
      db:
        condition: service_healthy


  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --requirepass fultang --port 6379
    restart: unless-stopped
    #ports:
    #  - 6379:6379
    networks:
      - fultang

  celery:
    image: "${FULTANG_IMAGE:-fultang:latest}"
    restart: always
    user: django-user
    command: [ "sh", "-c", "celery -A fultang worker --loglevel=info" ]
    volumes:
      - .:/app
    depends_on:
      - redis
      - fultang
    networks:
      - fultang

  celery-beat:
    image: "${FULTANG_IMAGE:-fultang:latest}"
    restart: always
    user: django-user
    command: [ "sh", "-c", "celery -A fultang beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler" ]
    volumes:
      - .:/app
    depends_on:
      - redis
      - fultang
    networks:
      - fultang

  fultang-frontend:
    build:
      context: ../ihm_fultang-frontend-v1
      dockerfile: Dockerfile
    container_name: fultang-frontend
    restart: always
    volumes:
      - ../ihm_fultang-frontend-v1:/app
      - /app/node_modules
    ports:
      - "9000:9000"
    env_file:
      - ../ihm_fultang-frontend-v1/.env
    depends_on:
      - fultang
    networks:
      - fultang

networks:
  fultang:
    driver: bridge

volumes:
  postgres_data:

