# Generated by Django 5.1.15 on 2026-01-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polyclinic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polyclinicproduct",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Running low", "Running Low"),
                    ("Out Of Stock", "Out Of Stock"),
                ],
                default="Available",
                max_length=20,
            ),
        ),
    ]
