# Generated by Django 4.2 on 2026-01-14 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polyclinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polyclinicproduct',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Running low', 'Running Low'), ('Discontinued', 'Discontinued'), ('Expiring Soon', 'Expiring Soon')], default='Available', max_length=20),
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField()),
                ('note', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('idMedicalStaff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idPatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polyclinic.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('PATIENT_CREATED', 'Patient Created'), ('SURGERY_SCHEDULED', 'Surgery Scheduled'), ('SURGERY_REMINDER', 'Surgery Reminder')], max_length=30)),
                ('priority', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], default='GREEN', max_length=10)),
                ('message', models.TextField()),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
