# Generated by Django 4.2 on 2026-01-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polyclinic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polyclinicproduct",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Running low", "Running Low"),
                    ("Discontinued", "Discontinued"),
                    ("Expiring Soon", "Expiring Soon"),
                ],
                default="Available",
                max_length=20,
            ),
        ),
    ]
