# Generated by Django 4.2 on 2025-11-18 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='busyBeds',
            new_name='occupiedBeds',
        ),
    ]
