# Generated by Django 4.2 on 2026-01-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0002_alter_polyclinicproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polyclinicproduct',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Out of Stock', 'Out of Stock'), ('Discontinued', 'Discontinued'), ('Expiring Soon', 'Expiring Soon')], default='Available', max_length=20),
        ),
    ]
