# Generated by Django 4.2 on 2025-11-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0002_rename_busybeds_room_occupiedbeds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='facilities',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('Simple', 'Simple'), ('Double', 'Double'), ('VIP', 'VIP'), ('Multiple', 'Multiple'), ('Emergency', 'Emergency'), ('Staff', 'Staff')], default='Simple', max_length=255),
        ),
    ]
