# Generated by Django 4.2 on 2026-01-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0003_alter_room_facilities_alter_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='addDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
