# Generated by Django 4.2 on 2026-01-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0004_room_adddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomNumber',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
