# Generated by Django 4.2 on 2026-01-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0005_alter_room_roomnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='examDescription',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
