# Generated by Django 4.2 on 2026-01-14 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polyclinic", "0002_alter_polyclinicproduct_status"),
        ("polyclinic", "0006_alter_exam_examdescription"),
    ]

    operations = []
