# Generated by Django 4.2 on 2026-01-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0007_alter_polyclinicproduct_status'),
        ('polyclinic', '0007_merge_20260114_1311'),
    ]

    operations = [
    ]
