# Generated by Django 4.2 on 2026-01-17 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0002_alter_polyclinicproduct_status_surgery_notification'),
        ('polyclinic', '0008_merge_20260117_1229'),
    ]

    operations = [
    ]
