# Generated by Django 4.2 on 2026-01-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic', '0009_merge_20260117_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationtype',
            name='typeDoctor',
            field=models.CharField(choices=[('Specialist', 'Specialist'), ('Ophthalmologist', 'Ophthalmologist'), ('Dentist', 'Dentist')], default='Specialist', max_length=100),
        ),
    ]
