# Generated by Django 5.1.15 on 2026-01-15 22:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_analyticaccount_budget_chartofaccounts_journal_and_more"),
        ("polyclinic", "0002_alter_polyclinicproduct_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountPeriodBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opening_debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "opening_credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "debit_movement",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "credit_movement",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "closing_debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "closing_credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Solde mensuel par compte",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "article_type",
                    models.CharField(
                        choices=[
                            ("DRUG", "Médicament"),
                            ("CONSUMABLE", "Consommable médical"),
                            ("EQUIPMENT", "Équipement"),
                            ("REAGENT", "Réactif laboratoire"),
                            ("SUPPLY", "Fourniture"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("UNIT", "Unité"),
                            ("BOX", "Boîte"),
                            ("BOTTLE", "Flacon"),
                            ("VIAL", "Ampoule"),
                            ("BAG", "Sachet"),
                            ("KG", "Kilogramme"),
                            ("LITER", "Litre"),
                            ("METER", "Mètre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "units_per_package",
                    models.PositiveIntegerField(
                        default=1, help_text="Nombre d'unités par conditionnement"
                    ),
                ),
                ("is_perishable", models.BooleanField(default=False)),
                (
                    "shelf_life_days",
                    models.PositiveIntegerField(
                        blank=True, help_text="Durée de validité en jours", null=True
                    ),
                ),
                (
                    "minimum_stock",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Seuil d'alerte",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "safety_stock",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Stock de sécurité",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "reorder_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Quantité de réapprovisionnement",
                        max_digits=15,
                    ),
                ),
                (
                    "weighted_average_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Prix Moyen Pondéré (PMP)",
                        max_digits=15,
                    ),
                ),
                (
                    "last_purchase_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Prix de vente unitaire",
                        max_digits=15,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "requires_batch",
                    models.BooleanField(
                        default=True, help_text="Gestion par lots obligatoire"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Article",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(max_length=100)),
                (
                    "internal_reference",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("manufacturing_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("reception_date", models.DateField()),
                (
                    "initial_quantity",
                    models.DecimalField(decimal_places=3, max_digits=15),
                ),
                (
                    "remaining_quantity",
                    models.DecimalField(decimal_places=3, max_digits=15),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Coût unitaire d'achat",
                        max_digits=15,
                    ),
                ),
                ("is_blocked", models.BooleanField(default=False)),
                ("blocking_reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Lot",
                "ordering": ["expiry_date", "reception_date"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Particulier"),
                            ("CORPORATE", "Entreprise"),
                            ("INSURANCE", "Assurance/Mutuelle"),
                            ("GOVERNMENT", "Organisme Public"),
                        ],
                        default="INDIVIDUAL",
                        max_length=15,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "payment_terms",
                    models.PositiveIntegerField(
                        default=0, help_text="Délai de paiement en jours"
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Client",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Depot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "depot_type",
                    models.CharField(
                        choices=[
                            ("PHARMACY", "Pharmacie"),
                            ("CENTRAL", "Magasin central"),
                            ("OPERATING_ROOM", "Bloc opératoire"),
                            ("LABORATORY", "Laboratoire"),
                            ("EMERGENCY", "Urgences"),
                            ("WARD", "Service hospitalisation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "allows_negative_stock",
                    models.BooleanField(
                        default=False,
                        help_text="Autorise les stocks négatifs (déconseillé)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Dépôt",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Famille",
                "verbose_name_plural": "Familles",
                "ordering": ["category", "code"],
            },
        ),
        migrations.CreateModel(
            name="GoodsIssueLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=15)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="PMP au moment de la sortie",
                        max_digits=15,
                    ),
                ),
                ("line_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Ligne bon de sortie",
                "ordering": ["issue", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="GoodsIssueNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_number", models.CharField(max_length=30, unique=True)),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("SALE", "Vente"),
                            ("CONSUMPTION", "Consommation service"),
                            ("TRANSFER_OUT", "Transfert sortant"),
                            ("DAMAGE", "Casse/Perte"),
                            ("EXPIRY", "Péremption"),
                            ("RETURN", "Retour fournisseur"),
                        ],
                        max_length=15,
                    ),
                ),
                ("issue_date", models.DateField()),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("CONFIRMED", "Confirmé"),
                            ("POSTED", "Comptabilisé"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="DRAFT",
                        max_length=15,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Bon de sortie",
                "ordering": ["-issue_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoodsReceiptLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("batch_number", models.CharField(max_length=100)),
                ("manufacturing_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "quantity_ordered",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Quantité commandée",
                        max_digits=15,
                    ),
                ),
                (
                    "quantity_received",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Quantité réellement reçue",
                        max_digits=15,
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "discount_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("line_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Ligne bon d'entrée",
                "ordering": ["receipt", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="GoodsReceiptNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_number", models.CharField(max_length=30, unique=True)),
                (
                    "receipt_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "Achat"),
                            ("TRANSFER_IN", "Transfert entrant"),
                            ("RETURN", "Retour"),
                            ("ADJUSTMENT", "Ajustement"),
                            ("INITIAL", "Stock initial"),
                        ],
                        max_length=15,
                    ),
                ),
                ("receipt_date", models.DateField()),
                (
                    "document_date",
                    models.DateField(help_text="Date du document fournisseur"),
                ),
                (
                    "supplier_invoice",
                    models.CharField(
                        blank=True, help_text="N° facture fournisseur", max_length=100
                    ),
                ),
                (
                    "delivery_note",
                    models.CharField(
                        blank=True, help_text="N° bon de livraison", max_length=100
                    ),
                ),
                (
                    "purchase_order",
                    models.CharField(
                        blank=True, help_text="N° commande", max_length=100
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("CONFIRMED", "Confirmé"),
                            ("POSTED", "Comptabilisé"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="DRAFT",
                        max_length=15,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Bon d'entrée",
                "ordering": ["-receipt_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inventory_number", models.CharField(max_length=30, unique=True)),
                (
                    "inventory_type",
                    models.CharField(
                        choices=[
                            ("ANNUAL", "Annuel"),
                            ("PERIODIC", "Périodique"),
                            ("ROTATING", "Tournant"),
                            ("EXCEPTIONAL", "Exceptionnel"),
                        ],
                        max_length=15,
                    ),
                ),
                ("inventory_date", models.DateField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planifié"),
                            ("IN_PROGRESS", "En cours"),
                            ("COMPLETED", "Terminé"),
                            ("VALIDATED", "Validé"),
                            ("POSTED", "Comptabilisé"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="PLANNED",
                        max_length=15,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Inventaire",
                "verbose_name_plural": "Inventaires",
                "ordering": ["-inventory_date"],
            },
        ),
        migrations.CreateModel(
            name="InventoryLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theoretical_quantity",
                    models.DecimalField(decimal_places=3, max_digits=15),
                ),
                (
                    "physical_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True)),
                ("counted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Ligne d'inventaire",
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "physical_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Quantité physique réelle",
                        max_digits=15,
                    ),
                ),
                (
                    "theoretical_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Quantité théorique (comptable)",
                        max_digits=15,
                    ),
                ),
                (
                    "reserved_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Quantité réservée (commandes en cours)",
                        max_digits=15,
                    ),
                ),
                (
                    "stock_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Valeur du stock (quantité × PMP)",
                        max_digits=15,
                    ),
                ),
                ("last_inventory_date", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Stock",
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movement_number", models.CharField(max_length=30, unique=True)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("IN", "Entrée"),
                            ("OUT", "Sortie"),
                            ("TRANSFER", "Transfert"),
                            ("ADJUSTMENT", "Ajustement"),
                            ("RETURN", "Retour"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "movement_reason",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "Achat"),
                            ("SALE", "Vente"),
                            ("CONSUMPTION", "Consommation"),
                            ("TRANSFER", "Transfert"),
                            ("INVENTORY", "Inventaire"),
                            ("EXPIRY", "Péremption"),
                            ("DAMAGE", "Casse/Perte"),
                            ("RETURN_SUPPLIER", "Retour fournisseur"),
                            ("RETURN_PATIENT", "Retour patient"),
                            ("INITIAL", "Stock initial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=15)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix unitaire (PMP pour sorties, coût pour entrées)",
                        max_digits=15,
                    ),
                ),
                ("total_value", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "operation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("accounting_date", models.DateField(blank=True, null=True)),
                ("reference_document", models.CharField(blank=True, max_length=100)),
                ("document_type", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("CONFIRMED", "Confirmé"),
                            ("POSTED", "Comptabilisé"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="DRAFT",
                        max_length=15,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Mouvement de stock",
                "ordering": ["-operation_date", "-created_at"],
            },
        ),
        migrations.RenameField(
            model_name="journalentryline",
            old_name="partner",
            new_name="partner_supplier",
        ),
        migrations.AddField(
            model_name="chartofaccounts",
            name="is_collective",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="is_reversed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="reversal_of",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reversed_by",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="voucher_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="accountstate",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="chartofaccounts",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_accounts",
                to="accounting.chartofaccounts",
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="montant",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.CheckConstraint(
                check=models.Q(state="DRAFT") | models.Q(total_debit=models.F("total_credit")),
                name="posted_entry_must_be_balanced",
            ),
        ),
        migrations.AddField(
            model_name="accountperiodbalance",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounting.chartofaccounts",
            ),
        ),
        migrations.AddField(
            model_name="accountperiodbalance",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounting.accountingperiod",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="preferred_supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preferred_articles",
                to="accounting.supplier",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="purchase_account",
            field=models.ForeignKey(
                help_text="Compte classe 6 (ex: 603x)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="article_purchases",
                to="accounting.chartofaccounts",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="sales_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Compte classe 7 (ex: 701x)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="article_sales",
                to="accounting.chartofaccounts",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="stock_account",
            field=models.ForeignKey(
                help_text="Compte classe 3 (ex: 331x)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="article_stocks",
                to="accounting.chartofaccounts",
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batches",
                to="accounting.article",
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.supplier",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="default_expense_account",
            field=models.ForeignKey(
                help_text="Compte charge classe 6 par défaut",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category_expense_accounts",
                to="accounting.chartofaccounts",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="default_stock_account",
            field=models.ForeignKey(
                help_text="Compte stock classe 3 par défaut",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category_stock_accounts",
                to="accounting.chartofaccounts",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounting.category"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="account",
            field=models.ForeignKey(
                help_text="Compte 411 correspondant",
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.chartofaccounts",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="journalentryline",
            name="partner_customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.customer",
            ),
        ),
        migrations.AddField(
            model_name="depot",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_depots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="depot",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="polyclinic.department",
            ),
        ),
        migrations.AddField(
            model_name="depot",
            name="manager",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_depots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="family",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="families",
                to="accounting.category",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="family",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounting.family"
            ),
        ),
        migrations.AddField(
            model_name="goodsissueline",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounting.article"
            ),
        ),
        migrations.AddField(
            model_name="goodsissueline",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.batch",
            ),
        ),
        migrations.AddField(
            model_name="goodsissuenote",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="goodsissuenote",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Service destinataire",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="polyclinic.department",
            ),
        ),
        migrations.AddField(
            model_name="goodsissuenote",
            name="depot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounting.depot"
            ),
        ),
        migrations.AddField(
            model_name="goodsissuenote",
            name="issued_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issued_goods",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="goodsissuenote",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="goodsissuenote",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                help_text="Patient (si vente/prescription)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="polyclinic.patient",
            ),
        ),
        migrations.AddField(
            model_name="goodsissuenote",
            name="prescription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="polyclinic.prescription",
            ),
        ),
        migrations.AddField(
            model_name="goodsissuenote",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validated_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="goodsissueline",
            name="issue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="accounting.goodsissuenote",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptline",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounting.article"
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_receipts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="depot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounting.depot"
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_goods",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.supplier",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validated_receipts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptline",
            name="receipt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="accounting.goodsreceiptnote",
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_inventories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="depot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounting.depot"
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="managed_inventories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validated_inventories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inventoryline",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounting.article"
            ),
        ),
        migrations.AddField(
            model_name="inventoryline",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.batch",
            ),
        ),
        migrations.AddField(
            model_name="inventoryline",
            name="counted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inventoryline",
            name="inventory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="accounting.inventory",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocks",
                to="accounting.article",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="depot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocks",
                to="accounting.depot",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounting.article"
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.batch",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="destination_depot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_movements",
                to="accounting.depot",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="source_depot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outgoing_movements",
                to="accounting.depot",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validated_movements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="accountperiodbalance",
            unique_together={("account", "period")},
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["article", "expiry_date"], name="accounting__article_cbce4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["is_blocked"], name="accounting__is_bloc_4d867a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="batch",
            unique_together={("article", "batch_number", "supplier")},
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["code"], name="accounting__code_0593dd_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["category", "family"], name="accounting__categor_72da40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["is_active"], name="accounting__is_acti_4254da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goodsissuenote",
            index=models.Index(
                fields=["issue_number"], name="accounting__issue_n_c3b054_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goodsissuenote",
            index=models.Index(
                fields=["depot", "issue_date"], name="accounting__depot_i_7488f8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="goodsissueline",
            unique_together={("issue", "sequence")},
        ),
        migrations.AddIndex(
            model_name="goodsreceiptnote",
            index=models.Index(
                fields=["receipt_number"], name="accounting__receipt_674e89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goodsreceiptnote",
            index=models.Index(
                fields=["depot", "receipt_date"], name="accounting__depot_i_aa01e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goodsreceiptnote",
            index=models.Index(
                fields=["supplier"], name="accounting__supplie_8643a2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="goodsreceiptline",
            unique_together={("receipt", "sequence")},
        ),
        migrations.AlterUniqueTogether(
            name="inventoryline",
            unique_together={("inventory", "article", "batch")},
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["article", "depot"], name="accounting__article_2ce3ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(fields=["depot"], name="accounting__depot_i_99b07d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together={("article", "depot")},
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["article", "operation_date"],
                name="accounting__article_12e969_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["source_depot", "operation_date"],
                name="accounting__source__2979f6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["destination_depot", "operation_date"],
                name="accounting__destina_2c0914_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["movement_type", "status"],
                name="accounting__movemen_49d739_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(fields=["batch"], name="accounting__batch_i_287b1c_idx"),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["reference_document"], name="accounting__referen_8fe91c_idx"
            ),
        ),
    ]
