# Generated by Django 4.2 on 2026-01-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_article_batch_category_depot_transfernote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingperiod',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
