# Generated by Django 4.2 on 2026-01-22 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0003_accountperiodbalance_article_batch_category_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsissueline',
            name='line_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='goodsissueline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='PMP au moment de la sortie', max_digits=15),
        ),
        migrations.AlterField(
            model_name='goodsissuenote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('VALIDATED', 'Validé (Réservé)'), ('CONFIRMED', 'Confirmé (Déduit)'), ('POSTED', 'Comptabilisé'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=15),
        ),
        migrations.CreateModel(
            name='TransferNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(max_length=30, unique=True)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyé'), ('RECEIVED', 'Reçu'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_transfers', to=settings.AUTH_USER_MODEL)),
                ('destination_depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='accounting.depot')),
                ('source_depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='accounting.depot')),
            ],
            options={
                'verbose_name': 'Transfert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.article')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.transfernote')),
            ],
            options={
                'verbose_name': 'Ligne transfert',
                'ordering': ['transfer', 'sequence'],
                'unique_together': {('transfer', 'sequence')},
            },
        ),
    ]
