# Generated by Django 4.2 on 2026-01-25 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_article_batch_category_depot_transfernote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockjournalentryline',
            name='partner_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.stockcustomer'),
        ),
        migrations.AlterField(
            model_name='stockjournalentryline',
            name='partner_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.stocksupplier'),
        ),
    ]
