# Generated by Django 4.2 on 2026-01-25 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_stockjournalentryline_partner_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceiptnote',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.stocksupplier'),
        ),
    ]
