# Generated by Django 4.2 on 2026-01-26 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_goodsreceiptnote_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preferred_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_articles', to='accounting.stocksupplier'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.stocksupplier'),
        ),
    ]
