# Generated by Django 4.2 on 2026-01-26 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_article_preferred_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinventoryline',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.stockinventory'),
        ),
    ]
