# Generated by Django 4.2 on 2026-01-26 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_accountingperiod_end_date_and_more'),
        ('accounting', '0007_alter_stockinventoryline_inventory'),
    ]

    operations = [
    ]
