# Generated by Django 4.2 on 2026-01-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_medicalstaff_accesslevel"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalstaff",
            name="profilePicture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
