# Generated by Django 4.2 on 2026-01-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_medicalstaff_accesslevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalstaff',
            name='role',
            field=models.CharField(choices=[('NoRole', 'NoRole'), ('Doctor', 'Doctor'), ('Receptionist', 'Receptionist'), ('Admin', 'Admin'), ('Nurse', 'Nurse'), ('Labtech', 'Labtech'), ('HRM', 'HRM'), ('Pharmacist', 'Pharmacist'), ('Cashier', 'Cashier'), ('NoRole', 'NoRole'), ('Accountant', 'Accountant'), ('Auditor', 'Auditor'), ('FinanceManager', 'FinanceManager'), ('MaterialAccountant', 'MaterialAccountant')], default='NoRole', max_length=20),
        ),
    ]
