# Generated by Django 4.2 on 2026-01-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_medicalstaff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalstaff',
            name='role',
            field=models.CharField(choices=[('NoRole', 'NoRole'), ('Doctor', 'Doctor'), ('Receptionist', 'Receptionist'), ('Admin', 'Admin'), ('Nurse', 'Nurse'), ('Labtech', 'Labtech'), ('HRM', 'HRM'), ('Pharmacist', 'Pharmacist'), ('Cashier', 'Cashier'), ('Specialist', 'Specialist'), ('Ophthalmologist', 'Ophthalmologist'), ('Dentist', 'Dentist'), ('NoRole', 'NoRole'), ('Accountant', 'Accountant'), ('MaterialAccountant', 'MaterialAccountant'), ('Auditor', 'Auditor'), ('FinanceManager', 'FinanceManager')], default='NoRole', max_length=20),
        ),
    ]
