# Generated by Django 4.2 on 2026-01-26 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_passwordresettoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
