export const AppRoutesPaths = {
  notFound: "*",
  adminHomePage: "/admin/home",
  welcomePage: "/",
  loginPage: "/login",
  forgottenPasswordPage: "/forgotten-password",

  // --- PHARMACY ROUTES ---
  // pharmacyRoot: "/pharmacy",
  pharmacyPage: "/pharmacy/dashboard",
  PharmacistPage: "/pharmacy/list",
  PharmacyMedication: "//pharmacy/Medication",
  pharmacyAdd: "/pharmacy/add",

  pharmacyPrescriptions: "/pharmacy/prescriptions",

  doctorPage: "/doctor/dashboard",
  ophthalmologistPage: "/ophthalmologist/dashboard",
  laboratoryAssistantPage: "/laboratory-assistant/home",
  receptionistPage: "/receptionist/patients",
  cashierPage: "/cashier/consultation-list",
  consultationsList: "/cashier/consultations-list",
  examsList: "/cashier/exams-list",
  hospitalisations: "/cashier/hospitalisations-list",
  financialReport: "/cashier/financial-report",
  specialistPage: "/specialist",
  nursePage: "/nurse/patients",
  nurseMedicalStaffsPage: "/nurse/medical-staff",
  consultationHistoryPage: "/nurse/patients/consultation-history/:id",
  helpCenterPage: "/help-center",
  patientDetailsPage: "/nurse/patients/take-parameters/:id",
  receptionistMedicalStaffsPage: "/receptionist/medical-staffs",
  appointmentsPage: "/receptionist/appointments",
  adminPatientListPage: "/admin/patient-list",
  addMedication: "/admin/add-drug",
  adminMedicationsListPage: "/admin/drugs-list",
  addMedicalStaff: "/admin/add-medical-staff",
  adminMedicalStaffListPage: "/admin/medical-staff-list",
  adminConsultationListPage: "/admin/consultation-list",
  adminAppointmentsListPage: "/admin/appointments-list",
  addExam: "/admin/add-exam",
  adminExamsListPage: "/admin/exams-list",
  adminHospitalRoomPage: "/admin/room-list",
  adminFinancialReportsPage: "/admin/financial-report",
  accountantPage: "/accountant/dashboard",
  adminConsultationDetailsPage: "/admin/consultation-list/details",
  laboratoryHistory: "/laboratory/exams-history",
  laboratoryCurrent: "/laboratory/current-exams",
  financialHistory: "/cashier/financial-history",
  accountDetails: "/accountant/account-details/:accountId",
  accountList: "/accountant/account-list",

  doctorPatientList: "/doctor/patients",
  doctorConsultationList: "/doctor/consultation-list",
  doctorConsultationDetailsPage: "/doctor/consultation-list/details/:id",
  doctorAppointment: "/doctor/appointments",
  doctorMessage: "/doctor/messages",
  doctorConsultationHistory: "/doctor/consultation-history",
  doctorConsultationHistoryDetails: "/doctor/consultation-history/details/:id",
  doctorExamList: "/doctor/exams-list",
  doctorPatientMedicalFolderPage: "/doctor/patients/medical-folder/:id",

  ophthaPatientList: "/opthalmologist/patients",
  ophthaConsultationList: "/ophthalmologist/consultation-list",
  ophthaConsultationHistory: "/ophthalmologist/consultation-history",
  ophthaAppointment: "/ophthalmologist/appointments",
  ophthaMessage: "/ophthalmologist/messages",

  nurseMessage: "/nurse/messages",
  receptionistMessage: "/receptionist/messages",
  laboratoryMessage: "/laboratory-assistant/messages",
  adminMessage: "/admin/messages",

  financialContributions: "/accountant/financial-contributions",
  financialReportsAccountant: "/accountant/financial-reports",

  createFactureAccountant: "/accountant/create-facture",

  laboratoryPatientList: "/laboratory-assistant/patient-list",
  laboratoryExamenList: "/laboratory-assistant/exams-list",
  laboratoryExamenDetail: "/laboratory-assistant/exams-list/details/:id",
  laboratoryExamenHistories: "/laboratory-assistant/exams-history",
  laboratoryExamResultDetails:
    "/laboratory-assistant/exams-history/details/:id",

  financialAccountantHome: "/accountant-financial/home",
  financialAccountantChartOfAccount: "/accountant-financial/chart-account",
  financialAccountantJournalEntries: "/accountant-financial/journat-entries",
  financialAccountantAccountingJournals:
    "/accountant-financial/accounting-journals",
  financialAccountantAccountingGrandLivre:
    "/accountant-financial/accounting-grand-livre",
  financialAccountantInvoices: "/accountant-financial/invoices",
  financialAccountantPayments: "/accountant-financial/payments",
  financialAccountantBudgets: "/accountant-financial/budgets",
  financialAccountantReports: "/accountant-financial/reports",
  financialAccountantCostAnalytic: "/accountant-financial/cost-analytic",

  billing: "/accountant-financial/billing",
  consultationAppointments: "/help-center/consultation-appointments",
  paymentsBilling: "/help-center/payments-billing",
  technicalIssues: "/help-center/technical-issues",
  faq: "/help-center/faq",

  customers: "/accountant-financial/customers",
  suppliers: "/accountant-financial/suppliers",
  fixedAssetsRegister: "/accountant-financial/fixed-assets-register",
  inventoryValuation: "/accountant-financial/inventory-valuation",
  financialAccountPayroll: "/accountant-financial/payroll",
  vatCalculation: "/accountant-financial/tva",
  taxDeclarations: "/accountant-financial/tax-declaration",
  taxCalendar: "/accountant-financial/tax-calendar",
  cashPositions: "/accountant-financial/cash-positions",
  bankReconciliation: "/accountant-financial/bank-reconciliation",
  budgetEntry: "/accountant-financial/budget-entry",
  periodClose: "/accountant-financial/period-close",
  financialRatios: "/accountant-financial/financial-ratios",
  profitabilityAnalysis: "/accountant-financial/profitability-analysis",
  financialStatements: "/accountant-financial/financial-statements",

  // Material Accounting Routes
  materialAccountingDashboard: "/material-accounting/dashboard",

  materialCategories: "/material-accounting/categories",
  materialArticles: "/material-accounting/articles",
  materialWarehouses: "/material-accounting/warehouses",
  materialSuppliers: "/material-accounting/suppliers",
  materialFamilies: "/material-accounting/families",

  materialStockLevels: "/material-accounting/stock-levels",
  materialBatches: "/material-accounting/batches",
  materialMovements: "/material-accounting/movements",

  materialReceipts: "/material-accounting/receipts",
  materialReceiptDetails: "/material-accounting/receipts/:id",
  materialIssues: "/material-accounting/issues",
  materialIssueDetails: "/material-accounting/issues/:id",
  materialTransfers: "/material-accounting/transfers",
  materialTransferDetails: "/material-accounting/transfers/:id",

  materialInventories: "/material-accounting/inventories",
  materialInventoryDetails: "/material-accounting/inventories/:id",

  materialStockCard: "/material-accounting/reports/stock-card",
  materialPerpetualInventory: "/material-accounting/reports/perpetual-inventory",
  materialABCAnalysis: "/material-accounting/reports/abc-analysis",
  materialTurnoverRate: "/material-accounting/reports/turnover-rate",
  materialReconciliation: "/material-accounting/reports/reconciliation"
};
