export const AppRoutesPaths = {
  notFound: "*",
  adminHomePage: "/admin/home",
  welcomePage: "/",
  loginPage: "/login",
  forgottenPasswordPage: "/forgotten-password",
  pharmacyPage: "/pharmacy",
  doctorPage: "/doctor/dashboard",
  laboratoryAssistantPage: "/laboratory-assistant/home",
  receptionistPage: "/receptionist/patients",
  cashierPage: "/cashier/consultation-list",
  consultationsList: "/cashier/consultations-list",
  examsList: "/cashier/exams-list",
  hospitalisations: "/cashier/hospitalisations-list",
  financialReport: "/cashier/financial-report",
  helpCenter: "/cashier/help-center",
  specialistPage: "/specialist",
  nursePage: "/nurse/patients",
  nurseMedicalStaffsPage: "/nurse/medical-staff",
  consultationHistoryPage: "/nurse/patients/consultation-history/:id",
  helpCenterPage: "/help-center",
  patientDetailsPage: "/nurse/patients/take-parameters/:id",
  receptionistMedicalStaffsPage: "/receptionist/medical-staffs",
  appointmentsPage: "/receptionist/appointments",
  adminPatientListPage: "/admin/patient-list",
  addMedication: "/admin/add-drug",
  adminMedicationsListPage: "/admin/drugs-list",
  addMedicalStaff: "/admin/add-medical-staff",
  adminMedicalStaffListPage: "/admin/medical-staff-list",
  adminConsultationListPage: "/admin/consultation-list",
  adminAppointmentsListPage: "/admin/appointments-list",
  addExam: "/admin/add-exam",
  adminExamsListPage: "/admin/exams-list",
  adminHospitalRoomPage: "/admin/room-list",
  adminFinancialReportsPage: "/admin/financial-report",
  accountantPage: "/accountant/dashboard",
  adminConsultationDetailsPage: "/admin/consultation-list/details",
  laboratoryHistory: "/laboratory/exams-history",
  laboratoryCurrent: "/laboratory/current-exams",
  financialHistory: "/cashier/financial-history",
  accountDetails: "/accountant/account-details/:accountId",
  accountList: "/accountant/account-list",
  doctorPatientList: "/doctor/patients",
  doctorConsultationList: "/doctor/consultation-list",
  doctorConsultationDetailsPage: "/doctor/consultation-list/details/:id",
  doctorAppointment: "/doctor/appointments",
  doctorConsultationHistory: "/doctor/consultation-history",
  doctorConsultationHistoryDetails: "/doctor/consultation-history/details/:id",
  doctorExamList: "/doctor/exams-list",
  doctorPatientMedicalFolderPage: "/doctor/patients/medical-folder/:id",
  financialContributions: "/accountant/financial-contributions",
  financialReportsAccountant: "/accountant/financial-reports",
  PharmacyMedication: "/pharmacyMedication",
  createFactureAccountant: "/accountant/create-facture",
  journalEntryList: "/accountant/journal-entries",
  createJournalEntry: "/accountant/create-journal-entry",

  laboratoryPatientList: "/laboratory-assistant/patient-list",
  laboratoryExamenList: "/laboratory-assistant/exams-list",
  laboratoryExamenDetail: "/laboratory-assistant/exams-list/details/:id",
  laboratoryExamenHistories: "/laboratory-assistant/exams-history",
  laboratoryExamResultDetails:
    "/laboratory-assistant/exams-history/details/:id",
  laboratoryNotification: "/laboratory-assistant/notifications",

  financialAccountantHome: "/accountant-financial/home",
  financialAccountantChartOfAccount: "/accountant-financial/chart-account",
  financialAccountantJournalEntries: "/accountant-financial/journat-entries",
  financialAccountantAccountingJournals:
    "/accountant-financial/accounting-journals",
  financialAccountantAccountingGrandLivre:
    "/accountant-financial/accounting-grand-livre",
  financialAccountantInvoices: "/accountant-financial/invoices",
  financialAccountantPayments: "/accountant-financial/payments",
  financialAccountantBudgets: "/accountant-financial/budgets",
  financialAccountantReports: "/accountant-financial/reports",
  financialAccountPayroll: "/accountant-financial/payroll-journal",
  financialAccountantCostAnalytic: "/accountant-financial/cost-analytic",
  billing: "/accountant-financial/billing",
  revenueByService: "/accountant-financial/revenue-by-service",
  accountsReceivable: "/accountant-financial/accounts-receivable", 
  suppliers: "/accountant-financial/suppliers",
  supplierInvoices: "/accountant-financial/supplier-invoices",
  payables: "/accountant-financial/payables",
  cashPositions: "/accountant-financial/cash-positions",
  bankReconciliation: "/accountant-financial/bank-reconciliation",
  cashFlowForecast: "/accountant-financial/cash-flow-forecast",
  fixedAssetsRegister: "/accountant-financial/fixed-asset-register",
  depreciation: "/accountant-financial/depreciation",
  inventoryValuation: "/accountant-financial/inventory-valuation",
  abcAnalysis: "/accountant-financial/abc-analysis",
  physicalInventory: "/accountant-financial/physical-inventory",
  vatCalculation: "/accountant-financial/vat-calculation",
  taxDeclarations: "/accountant-financial/tax-declarations",
  taxCalendar: "/accountant-financial/tax-calendar",
  financialRatios: "/accountant-financial/financial-ratios",
  profitabilityAnalysis: "/accountant-financial/profitability-analysis",
  executiveDashboard: "/accountant-financial/executive-dashboard",
  budgetEntry: "/accountant-financial/budget-entry",
  budgetVariance: "/accountant-financial/budget-variance",
  budgetAlerts: "/accountant-financial/budget-alerts",
  periodClose: "/accountant-financial/period-close",
  financialStatements: "/accountant-financial/financial-statements",
  customReports: "/accountant-financial/custom-reports",
};
